todo/urls.py
from django.urls import path

from todo.views import TagListView, TaskListView, TaskCreateView, TaskUpdateView, TaskDeleteView, TagCreateView, \
    TagUpdateView, TagDeleteView, changer_status_task

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("<int:pk>/changer_status_task/", changer_status_task, name="change-status-task")

]

app_name = "todo"

todo_list_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField(default=None)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField(to=Tag, related_name="tasks")

    class Meta:
        ordering = ["done", "created_at"]

    def __str__(self):
        return f"{self.content} {self.done}"

todo/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = "/"


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = "/"


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = "/"


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


def changer_status_task(request, pk):
    task = Task.objects.get(pk=pk)
    task.done = not task.done
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO</title>{% endblock %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>

<body>

  <div class="container-fluid head-page mt-4">

    <div class="row">
      <div class="col-sm-2">

        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}

      </div>
      <div class="col-sm-10">

        {% block content %}{% endblock %}

      </div>
    </div>
  </div>
</body>

</html>

templates/includes/sidebar.html
<ul class="nav nav-pills flex-column mb-auto navigation">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}" class="nav-link">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}" class="nav-link">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block title %}<title>Delete</title>{% endblock %}

{% block content %}
  <h1>Delete?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="substrate">
    <h1>{{ object|yesno:"Update,Create" }} tag</h1>
    <form action="" method="post" class="col-sm-6">
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

  {% block content %}
    <h1>
      Tags
      <a class="btn btn-primary" href="">Create</a>
    </h1>

    {% if tag_list %}
    <table class="table text-center">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a href="{% url 'todo:tag-update' tag.pk %}">Update</a></td>
        <td><a href="{% url 'todo:tag-delete' tag.pk %}">Delete</a></td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>You haven't any tags</p>
    {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block title %}<title>Delete</title>{% endblock %}

{% block content %}
  <h1>Delete?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="substrate">
    <h1>{{ object|yesno:"Update,Create" }} task</h1>
    <form action="" method="post" class="col-sm-6">
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <div class="box-flex">
    <h1>
      TODO list
      <a href="{% url 'todo:task-create' %}" class="btn btn-primary float-end">Add task</a>
    </h1>

  </div>
  {% if task_list %}
  {% for task in task_list %}
    <div class="bg-secondary mb-2" style="height: 2px"></div>
    <h3>
      {{ task.content }}
      {% if task.done %}
        <a href="{% url 'todo:change-status-task' pk=task.id %}" class="btn btn-secondary float-end">Undo</a>
      {% else %}
        <a href="{% url 'todo:change-status-task' pk=task.id %}" class="btn btn-success float-end">Complete</a>
      {% endif %}
    </h3>
    {% if task.done %}
      <p class="h3" style="color: green">Done</p>
    {% else %}
      <p class="h3" style="color: red">Not done</p>
    {% endif %}
    <p>Created: {{ task.created_at }}</p>
    {% if task.tags %}
      <p class="h4">Tags:
        {% for tag in task.tags.all %}
        {{ tag.name }}
        {% endfor %}
        <a href="{% url 'todo:task-update' pk=task.pk %}">Update</a>
        <a href="{% url 'todo:task-delete' pk=task.pk %}">Delete</a>
      </p>
    {% endif %}

  {% endfor %}
  {% else %}
    <p>You haven't any tasks</p>
  {% endif %}
{% endblock %}